- name: Install Grafana
  apt:
    deb: "https://dl.grafana.com/oss/release/grafana_{{ version }}_amd64.deb"  

- name: "Grafana configuration file copy"
  template:
    src: "grafana.conf.j2"
    dest: /etc/grafana/grafana.ini
  notify: event_restart_grafana

- name: "Grafana server started"
  service:
    name: grafana-server
    enabled: true
    state: started

- name: "Check if Grafana is accessible."
  uri:
    url: http://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:8080
    method: GET
    status_code: 200

- name: Change Grafana admin password
  shell: grafana-cli admin reset-admin-password {{ config.grafana_server.admin_password }}
  args:
    warn: no
