---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    prefixes:
      grandpa: '6772616e'
      babe: '62616265'
      im_online: '696d6f6e'
      authority_discovery: '61756469'


  tasks:
    - name: ==CREATE SERVERS== Validators
      include_tasks: tasks/create_validators_servers.yml

    - name: ==CREATE SERVERS== Common Nodes
      include_tasks: tasks/create_common_nodes_servers.yml

    - name:  ==CREATE SERVERS== Prometheus
      include_tasks: tasks/create_prometheus_server.yml

    - name: Template Inventory to inventory.ini
      template:
        src: inventory.ini.j2
        dest: inventory.ini

    - name: DOWNLOAD latest binaries
      include_tasks: tasks/download_latest_binaries.yml

    - name: Create keys and folders structure for every node
      include_tasks: tasks/generate_keystores.yml
      loop: 
        "{{ created_validators_servers.results }}"
      loop_control:
        loop_var: droplet

    - name: Create TEST_KEYS file
      include_tasks: tasks/create_test_keys.yml
      loop: 
        "{{ created_common_nodes.results }}"
      loop_control:
        loop_var: common_node
    

    - name: Generate SPEC file
      include_tasks: tasks/spec_generate.yml

    # - name: Show unventory
    #   debug: 
    #     msg: '{{ hostvars }}'
    #   tags:
    #     - debug
        

- hosts: validators
  user: root
  gather_facts: false
  roles:
    - validator

- hosts: common-nodes
  user: root
  gather_facts: false
  roles:
    - common-node

- hosts: prometheus
  user: root
  gather_facts: false
  roles:
    - { role: 'prometheus', tags: 'prometheus'}
    - { role: 'grafana', tags: 'grafana'}
