---
- name: Generate test keys
  shell: "{{ 'data/local/subkey -n robonomics generate' }}"
  with_sequence: count={{ config.common.test_keys_count }}
  register: test_keys

- name: Template test_keys to data/uploads/common/test_keys.json
  template:
    src: test_keys.json.j2
    dest: data/uploads/common/test_keys.json