---
- uri:                                                               
    url: https://api.github.com/repos/airalab/robonomics/releases/latest
    return_content: true                                             
  register: json_reponse  

- set_fact:
    robonomics_link: |
      {% set r = [] %}
      {% for a in json_reponse.json.assets -%}
      {% if ('robonomics-ubuntu' in a.browser_download_url and 'x86_64' in a.browser_download_url) -%}
        {% set r = r.append(a.browser_download_url) -%}
      {% endif -%}
      {% endfor -%}  
      {{ r }}
    subkey_link: |
      {% set r = [] %}
      {% for a in json_reponse.json.assets -%}
        {% if ('subkey-ubuntu' in a.browser_download_url and 'x86_64' in a.browser_download_url) -%}
          {% set r = r.append(a.browser_download_url) -%}
        {% endif -%}
      {% endfor -%}  
      {{ r }}

- name: Create data/uploads/common folder
  file:
    path: data/uploads/common
    state: directory
    mode: "0755"

- name: Create data/local folder
  file:
    path: data/local
    state: directory
    mode: "0755"

- name: Create ./tmp folder
  file:
    path: tmp
    state: directory
    mode: "0755"

###############################
### DOWNLOAD SUBKEY BINARY ####
############################### 
- get_url:                                                           
    url: "{{ subkey_link[0] }}"                       
    dest: tmp/subkey.tar.gz

- name: Extract subkey binary to data/uploads
  shell: /bin/tar -xf tmp/subkey.tar.gz -C data/local

- name: Remove file tmp/subkey.tar.gz
  file:
    path: tmp/subkey.tar.gz
    state: absent

################################
## DOWNLOAD ROBONOMICS BINARY ##
################################
- name: Create data/uploads/common directory if it does not exist
  file:
    path: data/uploads/common
    state: directory
    mode: "0755"

- name: Get ROBONOMICS binary archive
  get_url:                                                           
    url: "{{ robonomics_link[0] }}"                       
    dest: tmp/robonomics.tar.gz

- name: Extract robonomics binary to data/uploads
  shell: /bin/tar -xf tmp/robonomics.tar.gz -C data/uploads/common 

- name: Remove file tmp/robonomics.tar.gz
  file:
    path: tmp/robonomics.tar.gz
    state: absent