---
###############################
########## NETWORK  ###########
###############################
- name: ==NETWORK== Create NETWORK a directory if it does not exist
  file:
    path: data/uploads/nodes/{{ droplet.data.ip_address }}/network
    state: directory
    mode: "0755"

- name: ==NETWORK== Create secret_ed25519 for every node
  command: data/local/subkey generate-node-key ./data/uploads/nodes/{{ droplet.data.ip_address }}/network/secret_ed25519
  register: network_key
###############################
########## /NETWORK  ##########
############################### 


###############################
########## KEYSTORES  #########
############################### 
- name: ==KEYSTORES== Create a KEYSTORE directory if it does not exist
  file:
    path: data/uploads/nodes/{{ droplet.data.ip_address }}/keystore
    state: directory
    mode: "0755"

- name: ==KEYSTORES== Create keystore keys with prefixes
  include_tasks: tasks/create_keystore_file.yml
  loop: "{{ lookup('dict', prefixes) }}"
  loop_control:
    loop_var: prefix

- name: Set keys for current node
  set_fact:
    nodes_session_keys: "{{ nodes_session_keys | default([]) + [session_keys] }}"
###############################
########## /KEYSTORES  ########
###############################