---
##############################
######### bootNodes  #########
##############################
- name: Create keys for bootNodes URLs
  shell: data/local/subkey inspect-node-key data/uploads/nodes/"{{ item.data.ip_address }}"/network/secret_ed25519
  loop:
    "{{ created_validators_servers.results }}"
  register: bootNodes
  tags:
    - create
###############################
########## /bootNodes  ########
###############################


###############################
####### palletBalances  #######
###############################
- name: Create validators & sudo keys
  shell: data/local/subkey -n robonomics generate
  # shell: data/local/subkey generate
  with_sequence: count={{ created_validators_servers.results|length + 1}}
  register: validators
  tags:
    - create

- name: ==VALIDATORS KEYS== Create VALIDATORS KEYS directory if it does not exist
  file:
    path: data/local/keys/validators
    state: directory
    mode: "0755"
  tags:
    - create

- name: Create validators key files
  copy:
    dest: ./data/local/keys/validators/{{ item.stdout_lines[-1].split(' ')[-1] }}
    content: | 
      "{{ item.stdout_lines[0].split('`')[1] }}"
  tags:
    - create
  with_items: '{{ validators.results[:-1] }}'

- name: ==SUDO KEYS== Create SUDO KEYS directory if it does not exist
  file:
    path: data/local/keys/sudo
    state: directory
    mode: "0755"
  tags:
    - create

- name: Create SUDO key file
  copy:
    dest: ./data/local/keys/sudo/{{ validators.results[-1].stdout_lines[-1].split(' ')[-1] }}
    content: | 
      "{{ validators.results[-1].stdout_lines[0].split('`')[1] }}"

- set_fact:
    validators_keys: "{{ validators_keys | default([]) + [item.stdout_lines[-1].split(' ')[-1]] }}"
  with_items: '{{ validators.results }}'
###############################
####### /palletBalances #######
###############################


- name: Template a file to data/uploads/common/spec.json
  template:
    src: spec.json.j2
    dest: data/uploads/common/spec.json